sudo: required
language: clojure
script: lein do test, build-site
branches:
  only:
    - master
deploy:
  provider: pages
  repo: kouphax.github.com
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build
  on:
    branch: master
