sudo: required
language: clojure
script: lein do test, build-site
branches:
  only:
    - master
deploy:
  provider: pages
  repo: kouphax.github.com
  target-branch: master
  github-token: $GITHUB_TOKEN
  skip_cleanup: true
  local-dir: build
  verbose: true
  on:
    branch: master
