language: ruby
rvm:
  - 2.1.1
script:  bundle exec middleman build
env:
  global:
    secure: higi4lfhTlp7w2yJ5dVJpjnIYf9ohFcgdf6XCkE1B6staIqFSryvgL/v0Mb37wHAHjW5t3O0TjRY2azTiD6PMaCdj699uD2TpHD2rJIVfIlYwnt6L5aYWLcmzgDluiWkjGH13EJimmwz1p3GoXfYcWVlRkt8cS2weQ9v0ORtj5A=
after_script:
  - cd build
  - git config --global user.email "james@yobriefca.se"
  - git config --global user.name "travis-ci"  
  - git init
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${DEPLOY_TOKEN}:@github.com" > .git/credentials  
  - git remote add origin https://github.com/kouphax/travis-test.git
  - git add -A
  - git commit -m "Automated push from travis"
  - git push --force origin master