(ns briefcase.core-test
  (:require [clojure.test :refer :all]
            [briefcase.content.core :refer [to-slug]]
            [net.cgrand.enlive-html :as html]))


(deftest existing-title-to-uri-mappings
  (testing "make sure that the to-slug method correctly slugifies exisiting articles so we dont break links"
    (are [title expected] (= (to-slug title) expected)
        "Defocus" "defocus"
        "Building Command Line Apps with Clojure" "building-command-line-apps-with-clojure"
        "SPAs and Enabling CORS in Spark" "spas-and-enabling-cors-in-spark"
        "Adventures in Clojure Land" "adventures-in-clojure-land"
        "Convenient Colouring of Console Output in Scala" "convenient-colouring-of-console-output-in-scala"
        "Continuous Delivery & Boy Scouting Your Deployment Pipeline" "continuous-delivery-and-boy-scouting-your-deployment-pipeline"
        "Building Systems: Libraries and Frameworks" "building-systems-libraries-and-frameworks"
        "So Long  and Thanks for All the Code" "so-long-and-thanks-for-all-the-code"
        "LocalOnly Actions in Play!" "localonly-actions-in-play"
        "Activate on Heroku" "activate-on-heroku"
        "Tinsmith: Online Scala REPL/Worksheet" "tinsmith-online-scala-repl-slash-worksheet"
        "Play! 2 for Java Pluralsight Course" "play-2-for-java-pluralsight-course"
        "Web Summit" "web-summit"
        "Better Management Through Agile Teams" "better-management-through-agile-teams"
        "On Evangelism..." "on-evangelism-dot-dot-dot"
        "Try Things" "try-things"
        "So Unbecoming" "so-unbecoming"
        "Elsewhere" "elsewhere"
        "Culture Bubbles Up" "culture-bubbles-up"
        "Disciplined Agile Delivery" "disciplined-agile-delivery"
        "The Old \"Agile is for Developers\" Myth" "the-old-agile-is-for-developers-myth"
        "Micro Service Architecture" "micro-service-architecture"
        "Rice" "rice"
        "Hardening Sprints: Just Say No?" "hardening-sprints-just-say-no"
        "Teams or People?" "teams-or-people"
        "The 'New' Value Triangle" "the-new-value-triangle"
        "Screencasts with a JVM flavour" "screencasts-with-a-jvm-flavour"
        "Trello Cards: Materialising Trello Boards" "trello-cards-materialising-trello-boards"
        "Eg. Play 2.1 + Scala + Guice" "eg-play-2-dot-1-plus-scala-plus-guice"
        "Neo4J Talk: Using Graphs to Analyse Public Spending on International Development" "neo4j-talk-using-graphs-to-analyse-public-spending-on-international-development"
        "Vertical vs Horizontal Thinking" "vertical-vs-horizontal-thinking"
        "Technology Techsmology" "technology-techsmology"
        "Neo4J Talk in November" "neo4j-talk-in-november"
        "Learning Resources for Scala  Play! and Mongo" "learning-resources-for-scala-play-and-mongo"
        "StackMob Lightning Talk" "stackmob-lightning-talk"
        "Dependencies in JavaScript: Constructor  Setter or Global" "dependencies-in-javascript-constructor-setter-or-global"
        "Securely Serving Static Files on Heroku" "securely-serving-static-files-on-heroku"
        "Backend as a Service - Part One" "backend-as-a-service-part-one"
        "Fear of Code" "fear-of-code"
        "expect.kt - Testing Library for Kotlin" "expect-dot-kt-testing-library-for-kotlin"
        "Kotlin: Nullable Extensions" "kotlin-nullable-extensions"
        "Kotlin: Extension Functions" "kotlin-extension-functions"
        "Kotlin: Here's What I Think (For Now)" "kotlin-heres-what-i-think-for-now"
        "Technology in the Cloud" "technology-in-the-cloud"
        "Azure Website Workflow for Bosses" "azure-website-workflow-for-bosses"
        "[Quick and Dirty  Super Ugly ] Starter for 10 - Dropwizard" "quick-and-dirty-super-ugly-starter-for-10-dropwizard"
        "Quitsies  Well Sort Of" "quitsies-well-sort-of"
        "Super Basic Trello API Wrapper for Scala and Play" "super-basic-trello-api-wrapper-for-scala-and-play"
        "Two Hidden Gems in Play 2's Template Engine" "two-hidden-gems-in-play-2-s-template-engine"
        "Mobile  How Do I Develop Thee? Let Me Count the Ways (Long Version)" "mobile-how-do-i-develop-thee-let-me-count-the-ways-long-version"
        ".NET on a Diet" "dot-net-on-a-diet"
        "Monotouch: C# + iOS = Good Times" "monotouch-c-number-plus-ios-equals-good-times"
        "5 Years" "5-years"
        "Starter for 10 - Scala  Play 2 and Mongo" "starter-for-10-scala-play-2-and-mongo"
        "The Little Sacrifices" "the-little-sacrifices"
        "Strapping Young Lad v0.1.2 Released" "strapping-young-lad-v0-dot-1-2-released"
        "Infoshare 2012 Talk" "infoshare-2012-talk"
        "Strapping Young Lad - Project Template Token Replacer and Bootstrapper" "strapping-young-lad-project-template-token-replacer-and-bootstrapper"
        "Scala - A Tragedy in Two Parts - Part 1" "scala-a-tragedy-in-two-parts-part-1"
        "Alfred Hack for Web Developers" "alfred-hack-for-web-developers"
        "Rails is not a gateway drug" "rails-is-not-a-gateway-drug"
        "Setting the Selected Option in a Select with Selenium in Scala" "setting-the-selected-option-in-a-select-with-selenium-in-scala"
        "Done Spoked at DevWeek" "done-spoked-at-devweek"
        "Slim Generator for Octopress" "slim-generator-for-octopress"
        "rbenv and CodeRunner" "rbenv-and-coderunner"
        "Tinkering with Spark: A Micro Web Framework for Java" "tinkering-with-spark-a-micro-web-framework-for-java"
        "Speaking at NDC Oslo" "speaking-at-ndc-oslo"
        "sentimentalizer: A Ruby port of Sentan" "sentimentalizer-a-ruby-port-of-sentan"
        "Tinkering with minion.js" "tinkering-with-minion-dot-js"
        "Taking the Stairs" "taking-the-stairs"
        "The Estimation 4x4" "the-estimation-4x4"
        "Caveat Abstractor" "caveat-abstractor"
        "On Craftsmanship and Understanding  I Guess" "on-craftsmanship-and-understanding-i-guess"
        "Enterprise Scale" "enterprise-scale"
        "Using Parse in .NET and WP7" "using-parse-in-net-and-wp7"
        "Standing at the cusp of 2011... WTF?" "standing-at-the-cusp-of-2011-dot-dot-dot-wtf"
        "A Nancy Module that Behaves like a Rails Controller... Mother of God" "a-nancy-module-that-behaves-like-a-rails-controller-dot-dot-dot-mother-of-god"
        "Code Coverage and the Forces of Good" "code-coverage-and-the-forces-of-good"
        "Ugh. He's on about something mobiley again. Lord save us all!" "ugh-hes-on-about-something-mobiley-again-lord-save-us-all"
        "So This Mobile Stuff Then... (Techologies)" "so-this-mobile-stuff-then-dot-dot-dot-techologies"
        "Rolling Your Own PhoneGap with MonoTouch" "rolling-your-own-phonegap-with-monotouch"
        "So this mobile stuff then... (Hybrid)" "so-this-mobile-stuff-then-dot-dot-dot-hybrid"
        "Chutzpah 1.3 Released" "chutzpah-1-dot-3-released"
        "Out with the old..." "out-with-the-old-dot-dot-dot"
        "Speaking at DevWeek 2012" "speaking-at-devweek-2012"
        "Wednesday Tip: C# Type aliases" "wednesday-tip-c-number-type-aliases"
        "Innovation Waffle" "innovation-waffle"
        "GiveCamp Northern Ireland 2012" "givecamp-northern-ireland-2012"
        "Nancy JSONP Hook" "nancy-jsonp-hook"
        "Tinyweb.FluentSecurity v0.1 Released" "tinyweb-dot-fluentsecurity-v0-dot-1-released"
        "refORM: Death to ORMs in .NET" "reform-death-to-orms-in-net"
        "CoffeeScript the Awesome" "coffeescript-the-awesome"
        "DDDNorth Retrospective" "dddnorth-retrospective"
        "DDDBelfast Retrospective" "dddbelfast-retrospective"
        "Tinyweb Fluent Security" "tinyweb-fluent-security"
        "Personal Systems of (Dis)Organisation" "personal-systems-of-dis-organisation"
        "Talking at DDD North and Belfast" "talking-at-ddd-north-and-belfast"
        "Hackathon #2: Mobile" "hackathon-number-2-mobile"
        "Windows 8" "windows-8"
        "Tinkering with Agility: Honorable Mentions" "tinkering-with-agility-honorable-mentions"
        "Tinkering with Agility" "tinkering-with-agility"
        "Hackathon Retrospective" "hackathon-retrospective"
        "Life (in IT) Lesson #5372: Learning To Say No  Keep Having Fun" "life-in-it-lesson-number-5372-learning-to-say-no-keep-having-fun"
        "An Opinionated Project Structure" "an-opinionated-project-structure"
        "Micro Web Frameworks in .NET 101: Tinyweb" "micro-web-frameworks-in-net-101-tinyweb"
        "Baler v0.4.1 Released" "baler-v0-dot-4-1-released"
        "Get Excited and Make Things" "get-excited-and-make-things"
        "Debugging NSpec Tests: The DebuggerShim" "debugging-nspec-tests-the-debuggershim"
        "Micro Web Frameworks in .NET 101: Anna" "micro-web-frameworks-in-net-101-anna"
        "MicroORMs for .NET: Inserts  Updates & Delete" "microorms-for-net-inserts-updates-and-delete"
        "Baler v0.4 Released" "baler-v0-dot-4-released"
        "Thinking about Hackathons" "thinking-about-hackathons"
        "MicroORMs for .NET: Stored Procedures" "microorms-for-net-stored-procedures"
        "Baler v0.3 Released" "baler-v0-dot-3-released"
        "MicroORMs for .NET: Syntax - SELECTs" "microorms-for-net-syntax-selects"
        "MicroORMs for .NET: (Obligatory) Introduction (Post)" "microorms-for-net-obligatory-introduction-post"
        "Baler v0.2.1 Released and 2 New Extensions" "baler-v0-dot-2-1-released-and-2-new-extensions"
        "Baler Site now Live(ish)" "baler-site-now-live-ish"
        "Announcing Baler" "announcing-baler"
        "Turns Out I'm Not Doing my Job Very Well aka Sucks To Be Me" "turns-out-im-not-doing-my-job-very-well-aka-sucks-to-be-me"
        "Micro Web Frameworks in .NET Screencast: Nancy #1 - Hello World" "micro-web-frameworks-in-net-screencast-nancy-number-1-hello-world"
        "Micro Web Frameworks in .NET 101: Nancy" "micro-web-frameworks-in-net-101-nancy"
        "Micro Web Frameworks in .NET Screencast: Jessica #3 - Configuration" "micro-web-frameworks-in-net-screencast-jessica-number-3-configuration"
        "Micro Web Frameworks in .NET Screencast: Jessica #2 - Static Content" "micro-web-frameworks-in-net-screencast-jessica-number-2-static-content"
        "Micro Web Frameworks in .NET Screencast: Jessica #4 - Views" "micro-web-frameworks-in-net-screencast-jessica-number-4-views"
        "Screencasts Galore!  More or less." "screencasts-galore-more-or-less"
        "Micro Web Frameworks in .NET Screencast - Jessica #1 - Hello World" "micro-web-frameworks-in-net-screencast-jessica-number-1-hello-world"
        "Micro Web Frameworks in .NET 101: Jessica" "micro-web-frameworks-in-net-101-jessica"
        "Why Would You Use Micro Web Frameworks in .NET?" "why-would-you-use-micro-web-frameworks-in-net"
        "Further Adventures in Unit Testing Technologies" "further-adventures-in-unit-testing-technologies"
        "The First Day of the Rest of My Life" "the-first-day-of-the-rest-of-my-life"
        "On The Move" "on-the-move"
        "Providing a Foundation for .NET Projects using NuGet" "providing-a-foundation-for-net-projects-using-nuget"
        "Flashbag: Glimpse" "flashbag-glimpse"
        "Guerrilla Learning Experiment #2: FlashBags" "guerrilla-learning-experiment-number-2-flashbags"
        "Crucible Code Review Guidelines" "crucible-code-review-guidelines"
        "PowerMockup â Wireframe Toolkit for PowerPoint" "powermockup-a-wireframe-toolkit-for-powerpoint"
        "Technically Non-Technical: The Pomodoro Technique" "technically-non-technical-the-pomodoro-technique"
        "A Tale of Unit Testing Technologies" "a-tale-of-unit-testing-technologies"
        "Serialising .NET Resources to JSON for Web Apps" "serialising-net-resources-to-json-for-web-apps"
        "CoffeeScript: JavaScript sans Bad Parts" "coffeescript-javascript-sans-bad-parts"
        "Node.js Lightning Talk" "node-dot-js-lightning-talk"
        "Mobile Redirection for Web Applications in ASP.NET MVC" "mobile-redirection-for-web-applications-in-asp-dot-net-mvc"
        "Entity Framework: Code First - Head First" "entity-framework-code-first-head-first"
        "MvcConf2: Post Conference Rubdown" "mvcconf2-post-conference-rubdown"
        "jQuery 1.5 Released" "jquery-1-dot-5-released"
        ".NET Web Technology Stack in 2011 and Beyond...." "dot-net-web-technology-stack-in-2011-and-beyond-dot-dot-dot"
        "Using CoffeeScript in .NET" "using-coffeescript-in-net"
        "VS2010/MVC JavaScript Intellisense HTML âHackâ" "vs2010-slash-mvc-javascript-intellisense-html-ahacka"
        "Better JSON Serialisation for ASP.NET MVC" "better-json-serialisation-for-asp-dot-net-mvc"
        "The Razor View Engine" "the-razor-view-engine"
        "Underscore.js: The JavaScript Utility Library" "underscore-dot-js-the-javascript-utility-library"
        "Remote Validation in ASP.NET MVC 3 RC1" "remote-validation-in-asp-dot-net-mvc-3-rc1"
        "All Change! ValidateInputAttribute and SkipRequestValidation" "all-change-validateinputattribute-and-skiprequestvalidation"
        "Mobilize! Adapting the ASP.NET MVC Project Template for jQuery Mobile" "mobilize-adapting-the-asp-dot-net-mvc-project-template-for-jquery-mobile"
        "ValidateInputAttribute Changes in MVC3 (Beta 2)" "validateinputattribute-changes-in-mvc3-beta-2"
        "Unobtrusive JavaScript in MVC3" "unobtrusive-javascript-in-mvc3"
        "Practical jQuery Mobile with ASP.NET MVC" "practical-jquery-mobile-with-asp-dot-net-mvc"
        "ASP.NET MVC3 JsonValueProviderFactory" "asp-dot-net-mvc3-jsonvalueproviderfactory"
        "Client Side: Processing vs Responsiveness" "client-side-processing-vs-responsiveness"
        "< HEAD >ache: Including JavaScript in ASP.NET Master Pages" "<-head->ache-including-javascript-in-asp-dot-net-master-pages"
        "JavaScript Proxy Pattern" "javascript-proxy-pattern"
        "jQuery Mobile Quick Look" "jquery-mobile-quick-look"
        "T4MVC: Strong Typing vs Magic Strings" "t4mvc-strong-typing-vs-magic-strings"
        "Strong Typing vs. Magic Strings (Part II)" "strong-typing-vs-magic-strings-part-ii"
        "Multi-Touch Reactive Extensions" "multi-touch-reactive-extensions"
        "Webforms & jQuery: A Comparison" "webforms-and-jquery-a-comparison"
        "Microsoft's Trio of jQuery Plugins" "microsofts-trio-of-jquery-plugins"
        "jQuery 1.4.3 & jQuery Mobile Released" "jquery-1-dot-4-3-and-jquery-mobile-released"
        "Modernizr & RequireJS" "modernizr-and-requirejs"
        "Outside Events jQuery Plugin" "outside-events-jquery-plugin"
        "ASP.NET MVC 3 Preview 1 First Look" "asp-dot-net-mvc-3-preview-1-first-look"
        "CSS Hacks for IE - Unnecessary" "css-hacks-for-ie-unnecessary"
        ".less - Dynamic CSS for .NET" "dot-less-dynamic-css-for-net"
        "Lazy Function Definition Pattern" "lazy-function-definition-pattern"
        "LINQPad: Donât let the name fool you" "linqpad-donat-let-the-name-fool-you"
        "JavaScript Method Overloading" "javascript-method-overloading"
        "UpdatePanels & Alternatives" "updatepanels-and-alternatives")))


;(defn fetch-url [url]
;  (html/html-resource (java.net.URL. url)))

;(defn count-entries-on-page [url]
;  (count (html/select (fetch-url url) [:div.entries :h3])))


;(deftest migration-parity
;  (testing "list counts"
;    (are [live local] (= live local)
;      (count-entries-on-page "http://yobriefca.se/talks")       (count-entries-on-page "http://localhost:3000/talks")
;      (count-entries-on-page "http://yobriefca.se/screencasts") (count-entries-on-page "http://localhost:3000/screencasts")
;      (count-entries-on-page "http://yobriefca.se/projects")    (count-entries-on-page "http://localhost:3000/projects")
;      (count-entries-on-page "http://yobriefca.se/articles")    (count-entries-on-page "http://localhost:3000/articles"))))



